In [5]:
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
encoded_words

[3, 43, 16, 8, 41, 7, 3, 23, 25]

In [7]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [8]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [9]:
## Define the vocabulary size
voc_size=10000

In [10]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [11]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9364, 9403, 9967, 392],
 [9364, 9403, 9967, 3667],
 [9364, 3285, 9967, 5413],
 [884, 5506, 9351, 9885, 8256],
 [884, 5506, 9351, 9885, 441],
 [3763, 9364, 2569, 9967, 4],
 [2154, 192, 8574, 9885]]

In [12]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [13]:
import numpy as np

In [14]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9364 9403 9967  392]
 [   0    0    0    0 9364 9403 9967 3667]
 [   0    0    0    0 9364 3285 9967 5413]
 [   0    0    0  884 5506 9351 9885 8256]
 [   0    0    0  884 5506 9351 9885  441]
 [   0    0    0 3763 9364 2569 9967    4]
 [   0    0    0    0 2154  192 8574 9885]]


In [15]:
## feature representation
dim=10

In [16]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

2025-05-03 14:04:04.937241: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M3 Pro
2025-05-03 14:04:04.937322: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 18.00 GB
2025-05-03 14:04:04.937332: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 6.00 GB
2025-05-03 14:04:04.937415: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2025-05-03 14:04:04.937464: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [18]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 53ms/step


2025-05-03 14:04:53.262744: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.


array([[[ 3.52379121e-02,  4.28711884e-02,  2.99258493e-02,
         -4.39741872e-02,  4.21691053e-02, -2.00153589e-02,
         -4.84900363e-02,  2.59935968e-02,  4.08496708e-03,
          4.34446372e-02],
        [ 3.52379121e-02,  4.28711884e-02,  2.99258493e-02,
         -4.39741872e-02,  4.21691053e-02, -2.00153589e-02,
         -4.84900363e-02,  2.59935968e-02,  4.08496708e-03,
          4.34446372e-02],
        [ 3.52379121e-02,  4.28711884e-02,  2.99258493e-02,
         -4.39741872e-02,  4.21691053e-02, -2.00153589e-02,
         -4.84900363e-02,  2.59935968e-02,  4.08496708e-03,
          4.34446372e-02],
        [ 3.52379121e-02,  4.28711884e-02,  2.99258493e-02,
         -4.39741872e-02,  4.21691053e-02, -2.00153589e-02,
         -4.84900363e-02,  2.59935968e-02,  4.08496708e-03,
          4.34446372e-02],
        [-2.92509329e-02,  3.41395773e-02, -4.21987064e-02,
          2.47547068e-02, -1.99838281e-02,  1.05900168e-02,
         -8.37943703e-03,  6.14291430e-03,  1.613022

In [19]:
embedded_docs[0]

array([   0,    0,    0,    0, 9364, 9403, 9967,  392], dtype=int32)

In [20]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 29ms/step


array([[ 3.5237912e-02,  4.2871188e-02,  2.9925849e-02, -4.3974187e-02,
         4.2169105e-02, -2.0015359e-02, -4.8490036e-02,  2.5993597e-02,
         4.0849671e-03,  4.3444637e-02],
       [ 3.5237912e-02,  4.2871188e-02,  2.9925849e-02, -4.3974187e-02,
         4.2169105e-02, -2.0015359e-02, -4.8490036e-02,  2.5993597e-02,
         4.0849671e-03,  4.3444637e-02],
       [ 3.5237912e-02,  4.2871188e-02,  2.9925849e-02, -4.3974187e-02,
         4.2169105e-02, -2.0015359e-02, -4.8490036e-02,  2.5993597e-02,
         4.0849671e-03,  4.3444637e-02],
       [ 3.5237912e-02,  4.2871188e-02,  2.9925849e-02, -4.3974187e-02,
         4.2169105e-02, -2.0015359e-02, -4.8490036e-02,  2.5993597e-02,
         4.0849671e-03,  4.3444637e-02],
       [-2.9250933e-02,  3.4139577e-02, -4.2198706e-02,  2.4754707e-02,
        -1.9983828e-02,  1.0590017e-02, -8.3794370e-03,  6.1429143e-03,
         1.6130220e-02, -1.0245193e-02],
       [-9.9751242e-03, -4.9715232e-02,  2.4208572e-02, -4.5032945e-02,
   