#### BOW,TFIDF,Machine Learning Algorithms

1. Preprocessing And Cleaning
2. Train Test Split
3. BOW And TF-IDF (Sentences--->vectors) {Preventing Data Leakage}
4. Trained Our Models


In [2]:
import pandas as pd
messages=pd.read_csv('SpamClassifier-master/smsspamcollection/SMSSpamCollection',
                    sep='\t',names=["label","message"])

In [3]:
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [3]:
## Data Cleaning And Preprocessing
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/anurag2/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [4]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [5]:
corpus=[]
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-z]',' ',messages['message'][i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [6]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

## Create Bag Of Words

In [7]:
## Output Features
y=pd.get_dummies(messages['label'])
y=y.iloc[:,0].values

In [8]:
y

array([ True,  True, False, ...,  True,  True,  True])

In [9]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.20)

In [10]:
## Create the Bag OF Words model
from sklearn.feature_extraction.text import CountVectorizer
## for Binary BOW enable binary=True
cv=CountVectorizer(max_features=2500,ngram_range=(1,2))

In [11]:
len(X_train),len(y_train)

(4457, 4457)

In [12]:
## independent features
X_train=cv.fit_transform(X_train).toarray()
X_test=cv.transform(X_test).toarray()

In [13]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000, 
    formatter=dict(float=lambda x: "%.3g" % x))
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [14]:
cv.vocabulary_

{'call': 243,
 'messag': 1283,
 'miss': 1302,
 'miss call': 1305,
 'play': 1587,
 'comput': 393,
 'lor': 1191,
 'urgent': 2264,
 'ur': 2236,
 'award': 117,
 'complimentari': 392,
 'trip': 2183,
 'entri': 608,
 'claim': 342,
 'txt': 2200,
 'di': 511,
 'ls': 1211,
 'ur award': 2237,
 'roommat': 1764,
 'also': 53,
 'want': 2331,
 'anoth': 60,
 'friend': 738,
 'may': 1263,
 'plan': 1586,
 'bring': 213,
 'extra': 645,
 'tell': 2077,
 'know': 1088,
 'sure': 2040,
 'today': 2147,
 'number': 1457,
 'end': 592,
 'select': 1821,
 'receiv': 1705,
 'match': 1250,
 'pleas': 1590,
 'quot': 1674,
 'code': 359,
 'standard': 1976,
 'rate': 1680,
 'app': 74,
 'number end': 1459,
 'end select': 594,
 'select receiv': 1822,
 'receiv award': 1706,
 'match pleas': 1251,
 'pleas call': 1591,
 'call quot': 261,
 'claim code': 344,
 'oh': 1472,
 'mean': 1266,
 'send': 1827,
 'lol': 1183,
 'tri': 2179,
 'contact': 404,
 'draw': 549,
 'show': 1859,
 'prize': 1643,
 'guarante': 868,
 'land': 1097,
 'line': 1163,


In [15]:
from sklearn.naive_bayes import MultinomialNB

In [16]:
spam_detect_model=MultinomialNB().fit(X_train,y_train)

In [17]:
y_pred=spam_detect_model.predict(X_test)

In [18]:
from sklearn.metrics import accuracy_score,classification_report

In [19]:
accuracy_score(y_test,y_pred)

0.9829596412556054

In [20]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       False       0.98      0.90      0.94       153
        True       0.98      1.00      0.99       962

    accuracy                           0.98      1115
   macro avg       0.98      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115



### Creating The TF-IDF Model

In [66]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.20)

In [67]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv=TfidfVectorizer(max_features=2500,ngram_range=(1,2))
X_train=tv.fit_transform(X_train).toarray()
X_test=tv.transform(X_test).toarray()

In [68]:
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.199, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.536, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0,

In [69]:
tv.vocabulary_

{'mayb': 1270,
 'park': 1535,
 'place': 1583,
 'near': 1403,
 'hous': 964,
 'thank': 2090,
 'subscript': 2015,
 'rington': 1753,
 'uk': 2219,
 'mobil': 1326,
 'charg': 319,
 'month': 1348,
 'pleas': 1589,
 'confirm': 394,
 'repli': 1726,
 'ye': 2479,
 'mobil charg': 1328,
 'repli ye': 1731,
 'congratul': 397,
 'ur': 2244,
 'award': 123,
 'either': 579,
 'cd': 307,
 'gift': 774,
 'voucher': 2311,
 'free': 703,
 'entri': 598,
 'weekli': 2379,
 'draw': 548,
 'txt': 2201,
 'music': 1383,
 'tnc': 2133,
 'www': 2457,
 'ldew': 1125,
 'com': 372,
 'win': 2405,
 'ppmx': 1629,
 'age': 30,
 'congratul ur': 398,
 'ur award': 2245,
 'award either': 126,
 'either cd': 580,
 'cd gift': 308,
 'gift voucher': 776,
 'voucher free': 2313,
 'free entri': 708,
 'entri weekli': 599,
 'weekli draw': 2381,
 'draw txt': 551,
 'txt music': 2205,
 'music tnc': 1385,
 'tnc www': 2134,
 'www ldew': 2460,
 'ldew com': 1126,
 'com win': 374,
 'win ppmx': 2408,
 'ppmx age': 1630,
 'someon': 1923,
 'smoke': 1911,
 'ev

In [70]:
from sklearn.naive_bayes import MultinomialNB
spam_tfidf_model = MultinomialNB().fit(X_train, y_train)

In [71]:

#prediction
y_pred=spam_tfidf_model.predict(X_test)

In [72]:
score=accuracy_score(y_test,y_pred)
print(score)

0.9766816143497757


In [73]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.83      0.99      0.90       124
           1       1.00      0.97      0.99       991

    accuracy                           0.98      1115
   macro avg       0.92      0.98      0.95      1115
weighted avg       0.98      0.98      0.98      1115

